/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [ID], [Ad]
      ,[Soyad]
      ,[Doğum Tarihi]
      ,[Cinsiyet]
      ,[Medeni Durum]
      ,[E-posta]
      ,[Telefon Numarası]
      ,[Üniversite]
      ,[Bölümü]
      ,[Pozisyon]
      ,[Yabancı dil]
      ,[yabancıdilek]
      ,[Dil Bilgisi]
      ,[Bilgisayarbilgisiek]
      ,[yetenek]
      ,[referans]
      ,[Başarı-Ödül]
      ,[Hobi]
      ,[CV Yükleme]
      ,[Ön Yazı Yükleme]
  FROM [bitesfrontenddeneme]
  where ID=1